name: aggieland_saturday
description: Aggieland Saturday App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^1.3.0

  url_launcher: ^5.7.2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont_wght.ttf


